version: "3.3"
services:
  postgres:
    container_name: redis-cache-db
    image: postgres
    environment:
      POSTGRES_USER: javawhizz
      POSTGRES_PASSWORD: javawhizz
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: javawhizz
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_volume_data:/home/user/data:/data
    environment:
      REDIS_ARGS: --save 20 1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  redis_insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_volume_data:/db

volumes:
  redis_volume_data:
  redis_insight_volume_data:
  postgres:
    driver: local








